In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.zeros((3,2))  # 行列

In [4]:
a.shape

(3, 2)

In [5]:
np.arange(3,7)  # 左闭右开

array([3, 4, 5, 6])

In [11]:
b = np.linspace(0,1,5)  # 返回某个区间等间距的数，start，stop，sample sum，这里是返回五个数，默认值是50

In [7]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [12]:
np.random.rand(2,4)  # 随机生成数组

array([[0.24625715, 0.74077155, 0.7505223 , 0.08559941],
       [0.01060763, 0.83434801, 0.52576116, 0.55669701]])

In [9]:
a.dtype   # 数组默认数据类型是'float64'，创建数组时也可以通过dtype指定值的类型

dtype('float64')

In [13]:
c = np.zeros((2,3), dtype='int32')

In [15]:
c = c.astype(float)   # 转换数据类型
print(c.dtype)

float64


In [16]:
# 两个相同尺寸的数组可以直接进行四则运算
a = np.array([1,2,3])
b = np.array([4,5,6])

In [17]:
a+b

array([5, 7, 9])

In [18]:
a/b

array([0.25, 0.4 , 0.5 ])

In [19]:
np.dot(a,b)  # 点乘运算，a@b为矩阵乘法运算

32

In [20]:
np.sqrt(a)  # 求平方根运算

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.power(a,2)  # 指数运算
# np.log(a)

array([1, 4, 9])

In [22]:
# 也可以单独与一个数做乘法， 广播机制
a * 5

array([ 5, 10, 15])

In [23]:
# 有意思的是不同尺寸的数组也可以相加，运算前会将数组扩展到相同尺寸，对应位置再相加
a = np.array([[1],
        [2],
        [10]])
b = np.array([0,1,2])
a+b

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [10, 11, 12]])

In [24]:
print(a.min())
print(a.max())   # 返回数组最大最小值

1
10


In [25]:
print(np.argmin(a))
print(np.argmax(a))  # 返回数组最大最小值所在的索引，或写成a.argmin()是一样的

0
2


In [28]:
print(a.sum())
print(a.mean())
print(np.median(a))
print(a.var())      # 返回方差标准差
print(a.std())  

13
4.333333333333333
2.0
16.22222222222222
4.0276819911981905


In [29]:
# 如果数组是额外数组，可以指定axis按行索引或者按列索引，0表示列不变，数据按行索引；1表示行不变，数据按列索引
a = np.array([[1,2,3,4,5],
        [5,6,7,8,9]])
a.sum(axis=0)

array([ 6,  8, 10, 12, 14])

In [30]:
a[(a>3) & (a % 2) == 0]   # 可以筛选数组中数据

array([1, 2, 3, 4, 6, 8])

In [31]:
a[0, 0:2]   # 还可以进行数据切片

array([1, 2])

In [33]:
a[0,0:5:2]   # 按步长取数，步长为2

array([1, 3, 5])